name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  code_quality:
    name: Code Quality
    uses: heitorpolidoro/.github/.github/workflows/code_quality_analyzers.yml@python_matrix
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
    with:
      python_versions: |-
        "3.9"
        "3.8"
