name: Code Quality

on:
  workflow_run:
    workflows:
      - Later Python Versions
    types:
      - completed

jobs:
  code_quality:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    name: Code Quality
    uses: heitorpolidoro/.github/.github/workflows/code_quality_analyzers.yml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
